### ISSUE TITLE
Review public study

### ISSUE THREAD

**Issue by sbabyanusha** [knowledgesystems/curation-scrum#1352]
testing instance: https://triage.cbioportal.mskcc.org/study/summary?id=ihch_dkfz_2019

**Comment by ritikakundra** [comment]
- dkfz should be capitalized 
- The PubMed link looks incorrect
- Don't we use SEX instead of GENDER for our studies?
- We are calling it a WXS study but according to the Sequencing type column only 4 samples are sequenced on WXS rest are on panel. Should the description 
<img width="552" alt="Screen Shot 2022-09-26 at 1 02 11 PM" src="https://user-images.githubusercontent.com/12007862/192337534-2567ebb4-373c-407f-8700-8248eaa1e117.png">
be altered? What are the NAs then?
